### ISSUE TITLE
Create a issue template to add organization to the landscape

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/landscape#15]
Let's use issue forms in this case.

**Comment by benjagm** [comment]
@DhairyaMajmudar open to work on this?

**Comment by DhairyaMajmudar** [comment]
Yes would like to take this one : )

**Comment by benjagm** [comment]
Thanks Dhairya. I think we'll need a second generic issue template for standard issues or inquires with the Landscape.

**Comment by DhairyaMajmudar** [comment]
Along with that I will also add a PR template so that upcoming PRs description get consistent.

**Comment by benjagm** [comment]
Fixed with #20
