### ISSUE TITLE
Separating Standardization Adoption within Adopters

### ISSUE THREAD

**Issue by egekorkan** [json-schema-org/landscape#32]
I would like to change W3C WoT to one of the adopters under a standardization column. Open API and others can also go in that category. I will make a PR to test and can adapt accordingly. 

However, what happens to the current adopters is unclear. They can be companies, open-source projects I guess? Any opinions?

**Comment by benjagm** [comment]
Thanks for filing this issue Ege. This is a great idea,  and the perfect reason to quick off the discussion to decide how we are going to structure the Landscape. @Relequestual

**Comment by benjagm** [comment]
Thanks Ege! We implemented this and now is in production.

Tactically we decided for now to divide adopters between: Standards and Adopters (the rest)

**Comment by benjagm** [comment]
Is it ok id we close this issue?
