### ISSUE TITLE
[.github][actions]: Migrate data validation to Landscape2 Validation Action

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/landscape#42]
**Description:**
Currently, on every PR we run a custom workflow to validate data files including landscape.yml, settings.yml, guide.yml using build command provided by the landscape tool for our CI/CD workflow. I suggest that we use the official validator action for the PR and then we can maintain our custom deploy logic separately. This way, we won't have to maintain the tool's data validation manually incase there are any breaking changes given this warning on the repo.

> [!WARNING]  
> Landscape2 is at an early stage of development. There may be breaking changes in the future to the command usage, flags, and configuration file formats.

**Suggested Approach:**
 - I suggest that we migrate to the official action at [Landscape2 Validation Action](https://github.com/cncf/landscape2-validate-action), for our custom workflow.
 - We could split our current workflow into two separate workflows, one workflow to validate all files including settings, guide, data yaml and another workflow to deploy to cloudflare.

**Comment by aialok** [comment]
I am working on this.
Thank you  : )
