### ISSUE TITLE
Enhancement: Include a copyright notice in the footer.

### ISSUE THREAD

**Issue by aialok** [json-schema-org/landscape#50]
**Description:**
- It would be better to add a copyright notice in the footer. Currently, it is missing from our landscape.

![Screenshot from 2024-05-10 12-45-57](https://github.com/json-schema-org/landscape/assets/66772290/1a5fbc31-1a68-4b37-9222-8f875a7ae8d3)

![image](https://github.com/json-schema-org/landscape/assets/66772290/1f09245c-a934-4619-9175-f069bc8d6db3)

**Comment by DevMhrn** [comment]
Should i Work in these ? @benjagm

**Comment by benjagm** [comment]
Thanks @DevMhrn ! Please go ahead with this issue.

**Comment by k-vijay-05** [comment]
@benjagm is still the issue open . can i work on this?

**Comment by benjagm** [comment]
> @benjagm is still the issue open . can i work on this?

Please go ahead with it.
