### ISSUE TITLE
🐛 Bug - There is an issue in the workflow to build the landscape

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/landscape#75]
### Describe the bug

When approving the last PR I found an issue in the workflow's execution to build the landscape:

https://github.com/json-schema-org/landscape/actions/runs/10250107486/job/28662560096

### Steps To Reproduce

Access https://github.com/json-schema-org/landscape/actions/runs/10250107486/job/28662560096 and click re-run all jobs.

### Expected Behavior

Run successfuly

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DarhkVoyd** [comment]
I understand that this is caused because, while we have updated the build tool version in the `publish`` workflow, we are still using older versions in the `validate` workflow, which are incompatible with our updated structure.
