### ISSUE TITLE
🌐 Add new Standard - Verifiable Credentials

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/landscape#83]
### Organisation Name

Verifiable Crendentials Specification

### Describe about the organisation

https://www.w3.org/TR/vc-json-schema/

### Select in which list organisation is to be added

Standards

**Comment by k-vijay-05** [comment]
@benjagm can i work on this?

**Comment by benjagm** [comment]
> @benjagm can i work on this?

Please go ahead.
