### ISSUE TITLE
🌐 Add new Standard - FHIR

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/landscape#84]
### Organisation Name

FHIR

### Describe about the organisation

https://hl7.org/fhir/

### Select in which list organisation is to be added

Standards

**Comment by k-vijay-05** [comment]
@benjagm can i work on this?

**Comment by gregsdennis** [comment]
I wonder if we should push them to list us in that level 1 box. 

Also, have we verified what version they're using?

**Comment by Kashika23** [comment]
can i work on this issue?
